const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.Persist,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.destroy,
		C3.Behaviors.Follow,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.gamepad,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Behaviors.LOS,
		C3.Behaviors.Orbit,
		C3.Plugins.NinePatch,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.gamepad.Acts.VibrateDualRumble,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Follow.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Acts.SetX,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Behaviors.Sin.Cnds.CompareMagnitude,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Orbit.Cnds.IsEnabled,
		C3.Behaviors.Orbit.Acts.Unpin,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.StartFollowingCustomProperty,
		C3.Behaviors.Follow.Acts.SetCustomPropertyValue,
		C3.Behaviors.Follow.Exps.DelayedCustomPropertyValue,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value
	];
};
self.C3_JsPropNameTable = [
	{Axe: 0},
	{Bullet: 0},
	{AxeBullet: 0},
	{Rotate: 0},
	{Pin: 0},
	{AxeSpinning: 0},
	{Persist: 0},
	{AxeInStump: 0},
	{Physics: 0},
	{AxeTether: 0},
	{Chain: 0},
	{PlayerTether: 0},
	{Whip: 0},
	{Fade: 0},
	{Fire: 0},
	{DestroyOutsideLayout: 0},
	{Fireball: 0},
	{FireCheck: 0},
	{EventChecker: 0},
	{LockOn: 0},
	{PlayerDistance: 0},
	{Follow: 0},
	{Cat: 0},
	{canAttack: 0},
	{isDying: 0},
	{dead: 0},
	{Flash: 0},
	{Hero: 0},
	{isChecking: 0},
	{isSleeping: 0},
	{enteringWater: 0},
	{invincible: 0},
	{Timer: 0},
	{Player: 0},
	{currentZoneID: 0},
	{oldZoneID: 0},
	{autoControlActive: 0},
	{autoControlDown: 0},
	{autoControlUp: 0},
	{autoControlLeft: 0},
	{autoControlRight: 0},
	{cutscene: 0},
	{"8Direction": 0},
	{PlayerMovement: 0},
	{PlayerRolling: 0},
	{catDone: 0},
	{Cat2: 0},
	{Cat3: 0},
	{PlayerStunned: 0},
	{Keyboard: 0},
	{TestingText: 0},
	{isTyping: 0},
	{isDone: 0},
	{TypeText: 0},
	{TextBackground: 0},
	{Text: 0},
	{AJAX: 0},
	{JSON: 0},
	{Gamepad: 0},
	{TitleTextPlaceholder: 0},
	{SleepText: 0},
	{KeysText: 0},
	{DungeonText1: 0},
	{DungeonText2: 0},
	{isAttacking: 0},
	{isDead: 0},
	{originX: 0},
	{originY: 0},
	{canMove: 0},
	{attackDamage: 0},
	{Slime: 0},
	{targetY: 0},
	{SlimeDrop: 0},
	{SlimePuddle: 0},
	{QueenBossGhost: 0},
	{isActive: 0},
	{hp: 0},
	{releaseSouls: 0},
	{TutorialQueenBoss: 0},
	{grabArea: 0},
	{SlimeBossGrabZone: 0},
	{grabbing: 0},
	{caughtPlayer: 0},
	{canGrab: 0},
	{SlimeBoss: 0},
	{BossPortraits: 0},
	{direction: 0},
	{Skeleton: 0},
	{DestroyOutside: 0},
	{Bone: 0},
	{Fish: 0},
	{FishFireball: 0},
	{Fish2: 0},
	{Bat: 0},
	{MonsterDeath: 0},
	{Soul: 0},
	{SoulResidue: 0},
	{AxeHitWall: 0},
	{BossDamage: 0},
	{AxeBounceOff: 0},
	{Solid: 0},
	{SolidBlock: 0},
	{specialEvent: 0},
	{event: 0},
	{Zone: 0},
	{Ocean: 0},
	{OceanClouds: 0},
	{OceanSky: 0},
	{OceanSkyReflection: 0},
	{sendToX: 0},
	{sendToY: 0},
	{locked: 0},
	{Sine: 0},
	{Door: 0},
	{WarpToArea: 0},
	{whichLever: 0},
	{mirrored: 0},
	{Lever: 0},
	{FloorPit: 0},
	{TreeStumpLayer: 0},
	{zoomIn1: 0},
	{zoomIn2: 0},
	{dungeonWeather: 0},
	{ScrollTo: 0},
	{CutsceneCamera: 0},
	{sendToLayout: 0},
	{setDirection: 0},
	{setAngle: 0},
	{WarpToLayout: 0},
	{Rain: 0},
	{RainSplash: 0},
	{Tween: 0},
	{StormBlack: 0},
	{Water: 0},
	{enterDirection: 0},
	{WaterEdge: 0},
	{lockNumber: 0},
	{ClosingDoor: 0},
	{SolidBlockPlayerOnly: 0},
	{whichDoor: 0},
	{autoMoveDirection: 0},
	{DoorCloseTrigger: 0},
	{KeyDoor: 0},
	{BossDoor: 0},
	{active: 0},
	{ArrowHole: 0},
	{BackgroundChains: 0},
	{triggersWhat: 0},
	{PressureTile: 0},
	{KeyBlock: 0},
	{WaterShadows: 0},
	{TilemapA1: 0},
	{TilemapB1: 0},
	{TilemapB2: 0},
	{TilemapA2: 0},
	{TilemapC1: 0},
	{TilemapC2: 0},
	{TilemapD1: 0},
	{TilemapD2: 0},
	{TilemapE1: 0},
	{TilemapE2: 0},
	{TilemapF1: 0},
	{TilemapF2: 0},
	{movingAngle: 0},
	{Fox: 0},
	{Bug: 0},
	{Chicken: 0},
	{Dog: 0},
	{OldMan: 0},
	{Girl: 0},
	{OldLady: 0},
	{TextID: 0},
	{portraitID: 0},
	{EventBlock: 0},
	{LineOfSight: 0},
	{CastleDoorman: 0},
	{bossPortraitID: 0},
	{delay: 0},
	{textBlock: 0},
	{EventTouchBlock: 0},
	{Soldier: 0},
	{Farmer: 0},
	{Librarian: 0},
	{Historian1: 0},
	{KidOutsideGame: 0},
	{GirlOutsideGame: 0},
	{BallKid1: 0},
	{BallKid2: 0},
	{Nickel: 0},
	{Historian2: 0},
	{RunningKid: 0},
	{Historian3: 0},
	{GirlNearCastle: 0},
	{GameCornerGuy: 0},
	{Gladiator: 0},
	{Pot: 0},
	{PotPiece1: 0},
	{PotPiece2: 0},
	{WindVane: 0},
	{Orbit: 0},
	{Leaf: 0},
	{isOnFire: 0},
	{Bush: 0},
	{Heart: 0},
	{Zeni: 0},
	{Football: 0},
	{FootballShadow: 0},
	{WindVane2: 0},
	{RunningKidBoundary: 0},
	{whichTorchLit: 0},
	{GroundTorch: 0},
	{WallTorch: 0},
	{contents: 0},
	{amount: 0},
	{text: 0},
	{TreasureChest: 0},
	{Zeni2: 0},
	{Key: 0},
	{whichKeyShadow: 0},
	{KeyShadow: 0},
	{KeyUsed: 0},
	{flying: 0},
	{Arrow: 0},
	{Crystal: 0},
	{BigChestsFullSheet: 0},
	{BigTreasureChest: 0},
	{Bell: 0},
	{BellClapper: 0},
	{UI: 0},
	{Health: 0},
	{HealthBar: 0},
	{HP: 0},
	{Magic: 0},
	{MagicBar: 0},
	{MP: 0},
	{MPBall: 0},
	{HPHeart: 0},
	{UI9patch: 0},
	{UIBlack: 0},
	{ZeniUI: 0},
	{KeyUI: 0},
	{ZeniText: 0},
	{whichBottle: 0},
	{PotionUI: 0},
	{Fader: 0},
	{FaderCircle: 0},
	{WhiteFader: 0},
	{Portraits: 0},
	{MoveTo: 0},
	{LOSFar: 0},
	{LOSNear: 0},
	{Slimes: 0},
	{Animals: 0},
	{TargetableNPCs: 0},
	{Skeletons: 0},
	{Timer2: 0},
	{LineOfSight2: 0},
	{Fishes: 0},
	{ChainLinks: 0},
	{Bats: 0},
	{WidthHalf: 0},
	{HeightHalf: 0},
	{ScrollSpeed: 0},
	{waitTime: 0},
	{PreviousLink: 0},
	{AxeLayer: 0},
	{ItemDrop: 0},
	{moveAngle: 0},
	{RollAngle: 0},
	{timeToFade: 0},
	{CheckDistance: 0},
	{TextSpeed: 0},
	{DoorX: 0},
	{FloorPitX: 0},
	{whichDoors: 0},
	{randomRadius: 0},
	{DropValue: 0},
	{CreateX: 0},
	{CreateY: 0},
	{ItemJingleTime: 0},
	{healingAmount: 0},
	{AbilityFireball: 0},
	{AbilityThrowAxe: 0},
	{Attack: 0},
	{AxeReturning: 0},
	{AxeThrown: 0},
	{Bottle1: 0},
	{Bottle2: 0},
	{BottleFull1: 0},
	{BottleFull2: 0},
	{ChainAmountOfChains: 0},
	{CurrentTextID: 0},
	{Curse: 0},
	{Defense: 0},
	{FaderSize: 0},
	{FaderSpeed: 0},
	{ForestEvil: 0},
	{FoundAxe: 0},
	{Keys: 0},
	{Language: 0},
	{LineIndex: 0},
	{MaxHP: 0},
	{MaxMP: 0},
	{PlayerAttacking: 0},
	{PlayerCharging: 0},
	{PlayerDirection: 0},
	{PlayerSwimming: 0},
	{Rumble: 0},
	{RumbleStrengthAttack: 0},
	{RumbleStrengthHit: 0},
	{SendDirection: 0},
	{SendAngle: 0},
	{SendX: 0},
	{SendY: 0},
	{SpeedMovement: 0},
	{SpeedRolling: 0},
	{TextIndex: 0},
	{TryingToMoveDirection: 0},
	{Tutorial1: 0},
	{Tutorial2: 0},
	{Weather: 0},
	{ZeniDisplayed: 0},
	{ZeniTotal: 0},
	{ZoneClamp: 0}
];

self.InstanceType = {
	Axe: class extends self.ISpriteInstance {},
	AxeBullet: class extends self.ISpriteInstance {},
	AxeSpinning: class extends self.ISpriteInstance {},
	AxeInStump: class extends self.ISpriteInstance {},
	AxeTether: class extends self.ISpriteInstance {},
	Chain: class extends self.ISpriteInstance {},
	PlayerTether: class extends self.ISpriteInstance {},
	Whip: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	Fireball: class extends self.ISpriteInstance {},
	FireCheck: class extends self.ISpriteInstance {},
	EventChecker: class extends self.ISpriteInstance {},
	LockOn: class extends self.ISpriteInstance {},
	Cat: class extends self.ISpriteInstance {},
	Hero: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerMovement: class extends self.ISpriteInstance {},
	PlayerRolling: class extends self.ISpriteInstance {},
	Cat2: class extends self.ISpriteInstance {},
	Cat3: class extends self.ISpriteInstance {},
	PlayerStunned: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TestingText: class extends self.ITextInstance {},
	TypeText: class extends self.ITextInstance {},
	TextBackground: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Gamepad: class extends self.IInstance {},
	TitleTextPlaceholder: class extends self.ITextInstance {},
	SleepText: class extends self.ITextInstance {},
	KeysText: class extends self.ITextInstance {},
	DungeonText1: class extends self.ITextInstance {},
	DungeonText2: class extends self.ITextInstance {},
	Slime: class extends self.ISpriteInstance {},
	SlimeDrop: class extends self.ISpriteInstance {},
	SlimePuddle: class extends self.ISpriteInstance {},
	QueenBossGhost: class extends self.ISpriteInstance {},
	TutorialQueenBoss: class extends self.ISpriteInstance {},
	SlimeBossGrabZone: class extends self.ISpriteInstance {},
	SlimeBoss: class extends self.ISpriteInstance {},
	BossPortraits: class extends self.ISpriteInstance {},
	Skeleton: class extends self.ISpriteInstance {},
	Bone: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	FishFireball: class extends self.ISpriteInstance {},
	Fish2: class extends self.ISpriteInstance {},
	Bat: class extends self.ISpriteInstance {},
	MonsterDeath: class extends self.ISpriteInstance {},
	Soul: class extends self.ISpriteInstance {},
	SoulResidue: class extends self.ISpriteInstance {},
	AxeHitWall: class extends self.ISpriteInstance {},
	BossDamage: class extends self.ISpriteInstance {},
	SolidBlock: class extends self.ISpriteInstance {},
	Zone: class extends self.ISpriteInstance {},
	Ocean: class extends self.ISpriteInstance {},
	OceanClouds: class extends self.ITiledBackgroundInstance {},
	OceanSky: class extends self.ITiledBackgroundInstance {},
	OceanSkyReflection: class extends self.ITiledBackgroundInstance {},
	Door: class extends self.ISpriteInstance {},
	WarpToArea: class extends self.ISpriteInstance {},
	Lever: class extends self.ISpriteInstance {},
	FloorPit: class extends self.ISpriteInstance {},
	TreeStumpLayer: class extends self.ISpriteInstance {},
	CutsceneCamera: class extends self.ISpriteInstance {},
	WarpToLayout: class extends self.ISpriteInstance {},
	Rain: class extends self.ISpriteInstance {},
	RainSplash: class extends self.ISpriteInstance {},
	StormBlack: class extends self.ITiledBackgroundInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	WaterEdge: class extends self.ISpriteInstance {},
	ClosingDoor: class extends self.ISpriteInstance {},
	SolidBlockPlayerOnly: class extends self.ISpriteInstance {},
	DoorCloseTrigger: class extends self.ISpriteInstance {},
	KeyDoor: class extends self.ISpriteInstance {},
	BossDoor: class extends self.ISpriteInstance {},
	ArrowHole: class extends self.ISpriteInstance {},
	BackgroundChains: class extends self.ISpriteInstance {},
	PressureTile: class extends self.ISpriteInstance {},
	KeyBlock: class extends self.ISpriteInstance {},
	WaterShadows: class extends self.ISpriteInstance {},
	TilemapA1: class extends self.ITilemapInstance {},
	TilemapB1: class extends self.ITilemapInstance {},
	TilemapB2: class extends self.ITilemapInstance {},
	TilemapA2: class extends self.ITilemapInstance {},
	TilemapC1: class extends self.ITilemapInstance {},
	TilemapC2: class extends self.ITilemapInstance {},
	TilemapD1: class extends self.ITilemapInstance {},
	TilemapD2: class extends self.ITilemapInstance {},
	TilemapE1: class extends self.ITilemapInstance {},
	TilemapE2: class extends self.ITilemapInstance {},
	TilemapF1: class extends self.ITilemapInstance {},
	TilemapF2: class extends self.ITilemapInstance {},
	Fox: class extends self.ISpriteInstance {},
	Bug: class extends self.ISpriteInstance {},
	Chicken: class extends self.ISpriteInstance {},
	Dog: class extends self.ISpriteInstance {},
	OldMan: class extends self.ISpriteInstance {},
	Girl: class extends self.ISpriteInstance {},
	OldLady: class extends self.ISpriteInstance {},
	EventBlock: class extends self.ISpriteInstance {},
	CastleDoorman: class extends self.ISpriteInstance {},
	EventTouchBlock: class extends self.ISpriteInstance {},
	Soldier: class extends self.ISpriteInstance {},
	Farmer: class extends self.ISpriteInstance {},
	Librarian: class extends self.ISpriteInstance {},
	Historian1: class extends self.ISpriteInstance {},
	KidOutsideGame: class extends self.ISpriteInstance {},
	GirlOutsideGame: class extends self.ISpriteInstance {},
	BallKid1: class extends self.ISpriteInstance {},
	BallKid2: class extends self.ISpriteInstance {},
	Nickel: class extends self.ISpriteInstance {},
	Historian2: class extends self.ISpriteInstance {},
	RunningKid: class extends self.ISpriteInstance {},
	Historian3: class extends self.ISpriteInstance {},
	GirlNearCastle: class extends self.ISpriteInstance {},
	GameCornerGuy: class extends self.ISpriteInstance {},
	Gladiator: class extends self.ISpriteInstance {},
	Pot: class extends self.ISpriteInstance {},
	PotPiece1: class extends self.ISpriteInstance {},
	PotPiece2: class extends self.ISpriteInstance {},
	WindVane: class extends self.ISpriteInstance {},
	Leaf: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Zeni: class extends self.ISpriteInstance {},
	Football: class extends self.ISpriteInstance {},
	FootballShadow: class extends self.ISpriteInstance {},
	WindVane2: class extends self.ISpriteInstance {},
	RunningKidBoundary: class extends self.ISpriteInstance {},
	GroundTorch: class extends self.ISpriteInstance {},
	WallTorch: class extends self.ISpriteInstance {},
	TreasureChest: class extends self.ISpriteInstance {},
	Zeni2: class extends self.ISpriteInstance {},
	Key: class extends self.ISpriteInstance {},
	KeyShadow: class extends self.ISpriteInstance {},
	KeyUsed: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Crystal: class extends self.ISpriteInstance {},
	BigChestsFullSheet: class extends self.ISpriteInstance {},
	BigTreasureChest: class extends self.ISpriteInstance {},
	Bell: class extends self.ISpriteInstance {},
	BellClapper: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	Health: class extends self.ISpriteInstance {},
	HealthBar: class extends self.I9PatchInstance {},
	HP: class extends self.ISpriteInstance {},
	Magic: class extends self.ISpriteInstance {},
	MagicBar: class extends self.I9PatchInstance {},
	MP: class extends self.ISpriteInstance {},
	MPBall: class extends self.ISpriteInstance {},
	HPHeart: class extends self.ISpriteInstance {},
	UI9patch: class extends self.I9PatchInstance {},
	UIBlack: class extends self.ISpriteInstance {},
	ZeniUI: class extends self.ISpriteInstance {},
	KeyUI: class extends self.ISpriteInstance {},
	ZeniText: class extends self.ITextInstance {},
	PotionUI: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	FaderCircle: class extends self.ISpriteInstance {},
	WhiteFader: class extends self.ISpriteInstance {},
	Portraits: class extends self.ISpriteInstance {},
	Slimes: class extends self.ISpriteInstance {},
	Animals: class extends self.ISpriteInstance {},
	TargetableNPCs: class extends self.ISpriteInstance {},
	Skeletons: class extends self.ISpriteInstance {},
	Fishes: class extends self.ISpriteInstance {},
	ChainLinks: class extends self.ISpriteInstance {},
	Bats: class extends self.ISpriteInstance {}
}